wsusserver: Add configure proxy feature
TraGicCode/tragiccode-wsusserver pull request #19
Opened 2018-03-27 22:19 UTC by jblance

#### Pull Request (PR) description
Complete feature to configure wsusserver to use a proxy

#### This Pull Request (PR) fixes the following issues
    Fixes #7 

#### Task list

- [x ] Resource/Class documentation added/updated in README.md?
- [ x] Examples appropriately added/updated?
- [ ] Unit tests added/updated?
      See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible)?
      See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).

Testing done on development WSUS server

2018-03-27 22:22 UTC, TraGicCode commented
I Completely butchered the pr template.  let me fix that.

2018-03-27 22:33 UTC, TraGicCode commented
Thanks for contributing back.   Do you mind fixing the tests?

2018-04-03 20:57 UTC, jblance commented
Tests fixed

2018-05-04 12:50 UTC, TraGicCode commented
Hey @jblance ,

Hopefully i will obtain some time to review this soon.  Sorry for the wait and thanks again for the work.

2018-11-14 18:56 UTC, TraGicCode requested changes
Minor changes to get the tests passing.

2018-11-14 18:56 UTC, TraGicCode commented on spec/classes/config_spec.rb
> +    it { should contain_exec('wsus-config-update-synchronization').with({
Lets remove the checking of the command and unless attribute content from the test.  This stuff is super hard to maintain and gives way more headache and little value.

2018-11-20 11:54 UTC, TraGicCode commented
Also please rebase.

2021-01-21 02:45 UTC, closed without merging

2021-01-21 02:46 UTC, TraGicCode commented
Closing since this is an old pr