wsusserver: support product families
TraGicCode/tragiccode-wsusserver pull request #28
Opened 2019-02-19 03:53 UTC by nathangiuliani

#### Pull Request (PR) description

#### This Pull Request (PR) fixes the following issues

#### Task list
- [x] Resource/Class documentation added/updated in README.md?
- [x] Examples appropriately added/updated?
- [x] Unit tests added/updated?
- [ ] Integration tests added/updated (where possible)?

2019-02-19 06:08 UTC, TraGicCode commented
Hey @nathangiuliani ,

Can you rebase with master?

2019-02-19 06:40 UTC, nathangiuliani commented
> Hey @nathangiuliani ,
> 
> Can you rebase with master?

done

2019-02-22 04:09 UTC, TraGicCode requested changes
Minor formatting change

2019-02-22 04:09 UTC, TraGicCode commented on README.md
> +        product_families                   => [
can you fix the spacing/tabing here?

2019-02-28 01:11 UTC, TraGicCode commented
Hey @nathangiuliani ,

Thanks for working on this!

2019-02-28 01:12 UTC, TraGicCode approved these changes
LGTM

2019-02-28 01:12 UTC, merged